// Availability UI integration. All APIs are mocked; no intervention is booked.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const here=path.dirname(fileURLToPath(import.meta.url)),deps=path.resolve(here,process.env.ACJ_DOM_TEST_DEPS||'../../dom-test/node_modules');
const require=createRequire(path.join(deps,'acj-dom-test.cjs')),{JSDOM}=require(path.join(deps,'jsdom/lib/api.js'));
const source=fs.readFileSync(path.resolve(here,'../availability-v32.js'),'utf8');
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const response=data=>new Response(JSON.stringify(data),{status:200,headers:{'Content-Type':'application/json'}});
const normalize=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const nameMatches=(name,query)=>normalize(query).split(' ').filter(Boolean).every(token=>normalize(name).includes(token));
function slot(i,extra={}){return {date:`2030-01-${String(7+Math.floor(i/2)).padStart(2,'0')}`,start:i%2?'13:00':'09:00',end:i%2?'16:00':'12:00',intervenant:i%2?'Alex Jardin':'Camille Test',employee_key:'employee-'+i,id_intervenant:'ogust-'+i,source:i%2?'google':'ogust',employee_activity_checked:true,employee_base_configured:true,client_base_configured:true,verification:{complete:true,planning_complete:true,feasibility_complete:false,planning_checked:true,absences_checked:true,employee_base_checked:true,client_base_checked:true,employee_profile_checked:true,employee_activity_checked:true,employment_checked:false,agency_checked:false,travel_checked:false},...extra}}
const complete=slots=>({ok:true,count:slots.length,total_count:slots.length,checked_at:new Date().toISOString(),slots,sources:{ogust:{queried:true,available:true},google:{queried:true,available:true}},base_availability:{available:true},verification:{complete:true,warnings:[]}});
const line=(extra={})=>({id:'work-1',type:'service',unit:'h',qty:3,activity:'jardin',designation:'Travaux de jardinage',pricingMethod:'hourly',...extra});
async function boot(options={}){
  const dom=new JSDOM('<html><head></head><body><input id="client" value="Client Test"><input id="adresse" value="Rue du test"><section class="step" data-step="4"><div class="card">Devis</div><div class="card">Actions</div></section><div id="av31Panel"></div></body></html>',{url:'https://thomas-boudin.github.io/devis-ACJ/',runScripts:'outside-only'});
  const w=dom.window,calls=[];let data=complete(Array.from({length:16},(_,i)=>slot(i))),hold=null;
  w.state={company:'ACJ Services',number:'ACJ-TEST',mode:options.mode||'jardin',client:'Client Test',address:'Rue du test',lines:options.lines||[line()]};
  w.ogustClientChoiceV21={company:'ACJ Services',selected:options.noClient?null:{id_customer:'client-42',label:'Client Test'}};
  w.AbortController=AbortController;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};
  w.goStep=()=>{};w.renderQuoteLines=()=>{};w.setMode=n=>w.state.mode=n;w.applyImportedNotesClientV39=()=>{};
  w.newQuote=()=>{w.state={company:w.state.company,number:'ACJ-NEW',mode:'jardin',client:'',address:'',lines:[]};w.document.getElementById('client').value='';w.document.getElementById('adresse').value='';w.ogustClientChoiceV21.selected=null};
  w.quotePayload=()=>({numero_devis:w.state.number,societe:w.state.company});
  // The server filters preferences BEFORE applying its result limit.
  w.fetch=async(url,init)=>{const parsed=new URL(url);calls.push({url:parsed,init});if(hold)return hold.promise;if(!data.ok)return response(data);
    const employee=parsed.searchParams.get('employee_name')||'',weekday=parsed.searchParams.get('weekday'),period=parsed.searchParams.get('period');
    const matches=(data.slots||[]).filter(item=>(!employee||nameMatches(item.intervenant,employee))&&(weekday===null||!/^\d{4}-\d{2}-\d{2}$/.test(item.date)||new Date(`${item.date}T12:00:00Z`).getUTCDay()===Number(weekday))&&(period==='any'||period==='morning'&&item.end<='12:00'||period==='afternoon'&&item.start>='13:00'));
    return response({...data,slots:matches.slice(0,Number(parsed.searchParams.get('max_results')||80))});
  };
  w.eval(source);await wait(10);w.document.getElementById('av32From').value='2030-01-07';
  return {dom,w,doc:w.document,calls,setData(next){data=next},defer(){let resolve;const promise=new Promise(done=>resolve=done);hold={promise,resolve};return next=>{resolve(response(next));hold=null}}};
}
function event(app,id,value,name='change'){const node=app.doc.getElementById(id);node.value=String(value);node.dispatchEvent(new app.w.Event(name,{bubbles:true}));return node}
function allChoices(app){while(app.doc.getElementById('av32More'))app.doc.getElementById('av32More').click();return app.doc.querySelectorAll('.av32Slot').length}
const apps=[];async function make(options){const app=await boot(options);apps.push(app);return app}
try{
  const a=await make();assert.equal(a.doc.getElementById('av31Panel').style.display,'none');assert.equal(a.doc.getElementById('av32Duration').value,'3');assert.equal(a.doc.getElementById('av32ScopeField').hidden,true);assert.match(a.doc.getElementById('av32Conditions').textContent,/une seule personne/);
  event(a,'av32Period','morning');await a.w.acjAvailabilityV32.search();let request=a.calls.at(-1).url;
  assert.equal(request.searchParams.get('duration_minutes'),'180');assert.equal(request.searchParams.get('id_customer'),'client-42');assert.equal(request.searchParams.get('activity'),'jardin');assert.equal(request.searchParams.get('max_results'),'80');
  assert.equal(a.doc.querySelectorAll('.av32Slot').length,3);assert.equal(a.doc.querySelectorAll('.av32DateGroup').length,3);assert.match(a.doc.getElementById('av32Status').textContent,/8 horaires/);assert.match(a.doc.getElementById('av32Status').textContent,/Planning contrôlé/);assert.match(a.doc.getElementById('av32Status').textContent,/Trajets à confirmer/);assert.ok(a.doc.getElementById('av32Status').classList.contains('warn'));
  event(a,'av32Period','any');await a.w.acjAvailabilityV32.search();assert.equal(allChoices(a),16,'All returned alternatives remain accessible');
  event(a,'av32Employee','Alex Jardin','input');assert.equal(a.doc.querySelectorAll('.av32Slot').length,0);await a.w.acjAvailabilityV32.search();assert.equal(a.calls.at(-1).url.searchParams.get('employee_name'),'Alex Jardin');assert.equal(allChoices(a),8);
  event(a,'av32Weekday','1');await a.w.acjAvailabilityV32.search();assert.equal(a.calls.at(-1).url.searchParams.get('weekday'),'1');assert.equal(a.doc.querySelectorAll('.av32Slot').length,2);
  a.doc.querySelector('.av32Slot').click();assert.ok(a.w.acjAvailabilityV32.selected);assert.equal(a.w.state.availabilityProposal.needs_recheck,false);assert.match(a.doc.getElementById('av32Selected').textContent,/Aucune intervention n’est réservée/);assert.ok(a.w.quotePayload().availability_proposal);
  const remembered=a.w.acjAvailabilityV32.getDraft(),b=await make();assert.equal(b.w.acjAvailabilityV32.restore(remembered),true);assert.equal(b.w.acjAvailabilityV32.selected,null);assert.equal(b.w.state.availabilityProposal.needs_recheck,true);
  a.w.state.lines[0].designation='Autre chantier';a.w.renderQuoteLines();assert.equal(a.w.acjAvailabilityV32.selected,null,'Same hours, different work invalidates selection');assert.equal(a.w.state.availabilityProposal,undefined);assert.equal(a.doc.querySelectorAll('.av32Slot').length,0);
  a.w.state.lines[0].qty=4;a.w.renderQuoteLines();assert.equal(a.doc.getElementById('av32Duration').value,'4');event(a,'av32Duration','2','input');a.w.state.lines[0].qty=5;a.w.renderQuoteLines();assert.equal(a.doc.getElementById('av32Duration').value,'5');assert.equal(a.doc.getElementById('av32DurationReset').hidden,true);
  event(a,'av32Duration','2','input');assert.equal(a.doc.getElementById('av32DurationReset').hidden,false);a.doc.getElementById('av32DurationReset').click();assert.equal(a.doc.getElementById('av32Duration').value,'5');
  for(const extra of [{unit:'forfait',pricingMethod:'flat'},{unit:'unité',pricingMethod:'quantity'},{unit:'h',pricingMethod:'flat'}]){
    const unknown=await make({lines:[line(),line({id:'work-2',...extra})]});assert.equal(unknown.doc.getElementById('av32Duration').value,'');await unknown.w.acjAvailabilityV32.search();assert.equal(unknown.calls.length,0);assert.match(unknown.doc.getElementById('av32Status').textContent,/durée sur place/);
    event(unknown,'av32Duration','3','input');unknown.setData(complete([slot(0)]));await unknown.w.acjAvailabilityV32.search();assert.equal(unknown.calls.length,1);assert.equal(unknown.calls[0].url.searchParams.get('duration_minutes'),'180');unknown.doc.querySelector('.av32Slot').click();unknown.w.state.lines.push(line({id:'another-flat',unit:'forfait',pricingMethod:'flat'}));unknown.w.renderQuoteLines();assert.equal(unknown.w.acjAvailabilityV32.selected,null);assert.equal(unknown.doc.getElementById('av32Duration').value,'');
  }
  const actual=await make({mode:'bricol'});actual.setData(complete([slot(0)]));await actual.w.acjAvailabilityV32.search();assert.equal(actual.calls[0].url.searchParams.get('activity'),'jardin','Actual lines determine trade');
  const mixed=await make({lines:[line(),line({id:'clean',activity:'menage',qty:2})]});assert.equal(mixed.doc.getElementById('av32ScopeField').hidden,false);await mixed.w.acjAvailabilityV32.search();assert.equal(mixed.calls.length,0);event(mixed,'av32Scope','jardin');assert.equal(mixed.doc.getElementById('av32Duration').value,'3');mixed.setData(complete([slot(0)]));await mixed.w.acjAvailabilityV32.search();assert.equal(mixed.calls[0].url.searchParams.get('activity'),'jardin');assert.equal(mixed.calls[0].url.searchParams.get('duration_minutes'),'180');mixed.doc.querySelector('.av32Slot').click();
  const mixedDraft=mixed.w.acjAvailabilityV32.getDraft(),mixedReload=await make({lines:[line(),line({id:'clean',activity:'menage',qty:2})]});assert.equal(mixedReload.w.acjAvailabilityV32.restore(mixedDraft),true);assert.equal(mixedReload.doc.getElementById('av32Scope').value,'jardin');assert.equal(mixedReload.w.state.availabilityProposal.needs_recheck,true);mixedReload.w.state.lines[1].qty=8;mixedReload.w.renderQuoteLines();assert.equal(mixedReload.w.acjAvailabilityV32.restore(mixedDraft),false,'Restoration compares all work, not just selected hours');
  mixed.w.state.lines[1].qty=8;mixed.w.renderQuoteLines();assert.equal(mixed.w.acjAvailabilityV32.selected,null);
  const unclassified=await make({lines:[line({activity:'',aiProvenance:undefined})],mode:'bricol'});await unclassified.w.acjAvailabilityV32.search();assert.equal(unclassified.calls.length,0);event(unclassified,'av32Scope','menage');assert.equal(unclassified.doc.getElementById('av32Duration').value,'3');
  const legacy=await make({lines:[{id:'legacy',type:'service',unite:'h',quantite:3,activite:'jardin',designation:'Legacy',methode_chiffrage:'hourly'}]});assert.equal(legacy.doc.getElementById('av32Duration').value,'3');
  const diverse=await make();diverse.setData(complete([slot(0),slot(0,{intervenant:'Autre Test',employee_key:'other'}),slot(0,{intervenant:'Encore Test',employee_key:'third'}),slot(1),slot(2)]));await diverse.w.acjAvailabilityV32.search();
  const intervals=[...diverse.doc.querySelectorAll('.av32Slot')].map(node=>node.closest('.av32DateGroup').querySelector('.av32DayTitle').textContent+'|'+node.querySelector('.av32When').textContent);assert.equal(new Set(intervals).size,3);assert.equal(diverse.doc.querySelectorAll('.av32DateGroup').length,2);assert.equal(allChoices(diverse),5);
  diverse.setData(complete([slot(0),slot(0,{employee_key:'other',intervenant:'Autre Test'})]));await diverse.w.acjAvailabilityV32.search();assert.equal(diverse.doc.querySelectorAll('.av32Slot').length,1,'One interval is one featured choice');assert.equal(allChoices(diverse),2);
  const workers=await make({lines:[line({activity:'menage'})]});const unknownWorker=slot(0,{intervenant:'Élodie Jean Baptiste Test',employee_activity_checked:false,verification:{...slot(0).verification,employee_activity_checked:false}});
  workers.setData({...complete([]),employee_options:[{id_employee:'test',name:unknownWorker.intervenant,activity_checked:false}],employee_preference_required:true});await workers.w.acjAvailabilityV32.search();assert.equal(workers.doc.getElementById('av32Preferences').open,true);assert.equal(workers.doc.querySelector('datalist option').value,unknownWorker.intervenant);assert.match(workers.doc.getElementById('av32Status').textContent,/intervenant nommé/);
  workers.setData(complete([unknownWorker]));await workers.w.acjAvailabilityV32.search();assert.equal(workers.doc.querySelectorAll('.av32Slot').length,0);event(workers,'av32Employee','Test Elodie Jean-Baptiste','input');await workers.w.acjAvailabilityV32.search();assert.equal(workers.doc.querySelectorAll('.av32Slot').length,1,'Explicit normalized/reversed name permits a conditional worker');assert.match(workers.doc.querySelector('.av32Checks').textContent,/Métier salarié à confirmer/);
  const named=await make();named.setData(complete([slot(0,{intervenant:'Vincent Test'})]));event(named,'av32Employee','Vincent Test','input');await named.w.acjAvailabilityV32.search();assert.equal(named.doc.querySelectorAll('.av32Slot').length,1);
  const strict=await make();strict.setData(complete([slot(0),slot(0,{employee_key:'bad-date',date:'2030-02-30'}),slot(0,{employee_key:'bad-time',start:'25:00',end:'28:00'}),slot(0,{employee_key:'bad-minute',start:'09:70',end:'12:70'}),slot(0,{employee_key:'wrong-duration',end:'13:00'}),slot(0,{employee_key:'outside-window',date:'2030-03-01'}),slot(0,{employee_key:'unverified',verification:{complete:false}})]));await strict.w.acjAvailabilityV32.search();assert.equal(strict.doc.querySelectorAll('.av32Slot').length,1);assert.match(strict.doc.getElementById('av32Status').textContent,/exclus/);
  strict.doc.querySelector('.av32Slot').click();const realNow=strict.w.Date.now;strict.w.Date.now=()=>realNow()+5*60*1000+1;assert.equal(strict.w.acjAvailabilityV32.selected,null);assert.equal(strict.w.state.availabilityProposal.needs_recheck,true);assert.match(strict.doc.getElementById('av32Selected').textContent,/à revérifier/);strict.doc.querySelector('.av32Slot').click();assert.equal(strict.w.acjAvailabilityV32.selected,null);strict.w.Date.now=realNow;
  strict.setData({...complete([slot(0)]),checked_at:'2000-01-01T00:00:00Z'});await strict.w.acjAvailabilityV32.search();assert.equal(strict.doc.querySelectorAll('.av32Slot').length,0);assert.match(strict.doc.getElementById('av32Status').textContent,/trop ancien/);
  const noClient=await make({noClient:true});assert.match(noClient.doc.getElementById('av32Conditions').textContent,/Disponibilité du client à confirmer/);
  const guard=await make();guard.setData({ok:false,error:'OGUST_AVAILABILITY_INCOMPLETE',slots:[]});await guard.w.acjAvailabilityV32.search();assert.equal(guard.doc.querySelectorAll('.av32Slot').length,0);assert.match(guard.doc.getElementById('av32Status').textContent,/lecture complète/);
  const release=guard.defer(),pending=guard.w.acjAvailabilityV32.search();await wait(0);event(guard,'av32Employee','Alex','input');release(complete([slot(0)]));await pending;assert.equal(guard.doc.querySelectorAll('.av32Slot').length,0);assert.equal(guard.doc.getElementById('av32Search').disabled,false);
  event(guard,'av32Employee','','input');guard.setData(complete([slot(0)]));await guard.w.acjAvailabilityV32.search();guard.doc.querySelector('.av32Slot').click();event(guard,'adresse','Nouvelle adresse','input');await wait(0);assert.equal(guard.w.acjAvailabilityV32.selected,null);
  await guard.w.acjAvailabilityV32.search();guard.doc.querySelector('.av32Slot').click();guard.w.ogustClientChoiceV21.selected={id_customer:'other-client',label:'Other'};guard.w.goStep(4);assert.equal(guard.w.acjAvailabilityV32.selected,null);
  await guard.w.acjAvailabilityV32.search();guard.doc.querySelector('.av32Slot').click();guard.w.state.company='ACJ Services Lens';guard.w.ogustClientChoiceV21.company='ACJ Services Lens';guard.w.dispatchEvent(new guard.w.CustomEvent('acj:company-changed'));assert.equal(guard.w.acjAvailabilityV32.selected,null);assert.equal(guard.doc.querySelectorAll('datalist option').length,0);
  guard.w.newQuote();assert.equal(guard.doc.getElementById('av32Duration').value,'');assert.equal(guard.w.state.availabilityProposal,undefined);assert.equal(guard.w.acjAvailabilityV32.restore(remembered),false);
  for(const app of apps)assert.ok(app.calls.every(call=>!call.init?.method||call.init.method==='GET'));
  console.log('Availability v49: onsite duration/scoped actual trades, full work guards, diversified three/all alternatives, server prefs, named conditional workers, strict date/time/duration, expiry and read-only failures OK');
}finally{await wait(10);for(const app of apps)app.dom.window.close()}
