// Full-job scheduling UI. API reads are mocked; no calendar/business write occurs.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const here=path.dirname(fileURLToPath(import.meta.url)),deps=path.resolve(here,process.env.ACJ_DOM_TEST_DEPS||'../../dom-test/node_modules');
const require=createRequire(path.join(deps,'acj-dom-test.cjs')),{JSDOM}=require(path.join(deps,'jsdom/lib/api.js'));
const source=fs.readFileSync(path.resolve(here,'../availability-v32.js'),'utf8'),wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const clone=value=>JSON.parse(JSON.stringify(value)),response=data=>new Response(JSON.stringify(data),{status:200,headers:{'Content-Type':'application/json'}});
const proof=()=>({planning_complete:true,planning_checked:true,absences_checked:true,employee_profile_checked:true,employee_base_checked:true,client_base_checked:true,client_planning_checked:true,feasibility_complete:false});
const options=[{id_employee:'a',name:'Alex Test',source:'ogust',activity_checked:true},{id_employee:'b',name:'Camille Test',source:'google',activity_checked:true},{id_employee:'c',name:'Morgan Test',source:'ogust',activity_checked:true},{id_employee:'u',name:'Élodie Jean Baptiste Test',source:'ogust',activity_checked:false}];
function nextDate(date){const d=new Date(`${date}T12:00:00Z`);do{d.setUTCDate(d.getUTCDate()+1)}while(d.getUTCDay()===0);return d.toISOString().slice(0,10)}
const time=minutes=>`${String(Math.floor(minutes/60)).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}`;
function plan({labor=180,persons=1,date='2030-01-07',ids=options.slice(0,persons).map(e=>e.id_employee),daily=480,start=480}={}){
  const crew=ids.map(id=>({...options.find(employee=>employee.id_employee===id)}));let remaining=Math.ceil(labor/persons),clock=start,dayUsed=0;const segments=[];
  while(remaining>0){if(clock>=1080||dayUsed>=daily){date=nextDate(date);clock=480;dayUsed=0}if(clock===720)clock=780;
    const end=Math.min(clock<720?720:1080,clock+remaining,clock+daily-dayUsed),duration=end-clock;
    segments.push({date,start:time(clock),end:time(end),onsite_minutes:duration,labor_minutes:duration*persons,employee_ids:[...ids],verification:proof(),assumptions:[],conditions:{}});remaining-=duration;dayUsed+=duration;clock=end;
  }
  const onsite=segments.reduce((sum,segment)=>sum+segment.onsite_minutes,0);
  return {id:'job_'+date+'_'+ids.join('_')+'_'+labor+'_'+start,persons,crew,segments,requested_labor_minutes:labor,planned_labor_minutes:onsite*persons,onsite_minutes:onsite,round_up_labor_minutes:onsite*persons-labor,day_count:new Set(segments.map(segment=>segment.date)).size,segment_count:segments.length,daily_minutes:daily,complete:true,verification:{planning_complete:true,feasibility_complete:false},conditions:{employee_activity_confirmed:crew.every(member=>member.activity_checked),employee_hours_configured:true,client_hours_configured:true,employment_confirmed:false,agency_confirmed:false,travel_confirmed:false},assumptions:[],pause:{start:'12:00',end:'13:00'}};
}
const complete=plans=>({ok:true,planning_mode:'job',checked_at:new Date().toISOString(),plans,employee_options:options,verification:{planning_complete:true,feasibility_complete:false},sources:{ogust:{queried:true,available:true},google:{queried:true,available:true}}});
const line=extra=>({id:'work-1',type:'service',unit:'h',qty:3,activity:'jardin',designation:'Travaux de jardinage',pricingMethod:'hourly',unitPriceTTC:47,...extra});
const apps=[];
async function boot(settings={}){
  const dom=new JSDOM('<html><head></head><body><input id="client" value="Client Test"><input id="adresse" value="Rue du test"><section class="step" data-step="4"><div class="card">Devis</div><div class="card">Actions</div></section><div id="av31Panel"></div></body></html>',{url:'https://thomas-boudin.github.io/devis-ACJ/',runScripts:'outside-only'}),w=dom.window,calls=[];
  let data=complete([plan(),plan({date:'2030-01-08'}),plan({start:780})]),held=null;
  w.state={company:'ACJ Services',number:'ACJ-TEST',mode:settings.mode||'jardin',client:'Client Test',address:'Rue du test',lines:settings.lines||[line()]};
  w.ogustClientChoiceV21={company:'ACJ Services',selected:settings.noClient?null:{id_customer:'client-42',label:'Client Test'}};w.AbortController=AbortController;
  w.goStep=()=>{};w.renderQuoteLines=()=>{};w.setMode=mode=>w.state.mode=mode;w.applyImportedNotesClientV39=()=>{};
  w.newQuote=()=>{w.state={company:w.state.company,number:'NEW',mode:'jardin',client:'',address:'',lines:[]};w.document.getElementById('client').value='';w.document.getElementById('adresse').value='';w.ogustClientChoiceV21.selected=null};w.quotePayload=()=>({numero_devis:w.state.number,societe:w.state.company});
  w.fetch=async(url,init)=>{calls.push({url:new URL(url),init});return held?held.promise:response(data)};
  w.eval(source);await wait(10);w.document.getElementById('av32From').value='2030-01-07';
  const app={dom,w,doc:w.document,calls,setData(value){data=value},defer(){let resolve;held={promise:new Promise(done=>resolve=done)};return value=>{held=null;resolve(response(value))}}};apps.push(app);return app;
}
function event(app,id,value,name='change'){const node=app.doc.getElementById(id);node.value=String(value);node.dispatchEvent(new app.w.Event(name,{bubbles:true}));return node}
function parallel(app){const checkbox=app.doc.getElementById('av32ParallelConfirm');checkbox.checked=true;checkbox.dispatchEvent(new app.w.Event('change',{bubbles:true}))}
function choose(app,id){const checkbox=app.doc.querySelector(`input[data-employee-id="${id}"]`);assert.ok(checkbox,'Named employee checkbox exists');checkbox.checked=true;checkbox.dispatchEvent(new app.w.Event('change',{bubbles:true}))}
const count=app=>app.doc.querySelectorAll('.av32Plan').length;
function clickPlan(app){const button=app.doc.querySelector('.av32Slot');assert.ok(button,'A full plan is selectable');button.click()}
try{
  const a=await boot();assert.equal(a.doc.getElementById('av32Duration').value,'3');assert.equal(a.doc.getElementById('av32Persons').value,'1');assert.equal(a.doc.getElementById('av32DailyHours').value,'8');assert.equal(a.doc.getElementById('av32Parallel').hidden,true);
  await a.w.acjAvailabilityV32.search();let query=a.calls.at(-1).url.searchParams;assert.equal(query.get('planning_mode'),'job');assert.equal(query.get('labor_minutes'),'180');assert.equal(query.get('persons'),'1');assert.equal(query.get('daily_minutes'),'480');assert.equal(query.get('duration_minutes'),null);assert.equal(query.get('employee_name'),null);assert.equal(query.get('id_customer'),'client-42');assert.equal(count(a),3);assert.match(a.doc.getElementById('av32Status').textContent,/couvrant tout le chantier/);assert.match(a.doc.querySelector('.av32Checks').textContent,/Trajets à confirmer/);
  clickPlan(a);assert.ok(a.w.acjAvailabilityV32.selected);assert.equal(a.w.state.availabilityProposal.version,3);assert.ok(a.w.state.availabilityProposal.plan);assert.match(a.doc.getElementById('av32Selected').textContent,/Aucune intervention n’est réservée/);const remembered=a.w.acjAvailabilityV32.getDraft();assert.ok(a.w.quotePayload().availability_proposal.plan);
  const reload=await boot();assert.equal(reload.w.acjAvailabilityV32.restore(remembered),true);assert.equal(reload.w.acjAvailabilityV32.selected,null);assert.equal(reload.w.state.availabilityProposal.needs_recheck,true);
  for(const broken of [null,[],[{date:'2030-01-07'}]]){const corrupt=clone(remembered);corrupt.proposal.plan.segments=broken;reload.w.state.availabilityProposal=clone(corrupt.proposal);assert.doesNotThrow(()=>reload.w.acjAvailabilityV32.restore(corrupt),'Draft consumer already copied malformed proposal into state');assert.equal(reload.w.state.availabilityProposal,undefined);assert.doesNotThrow(()=>reload.w.acjAvailabilityV32.getDraft());assert.doesNotThrow(()=>reload.w.quotePayload());assert.equal(reload.w.acjAvailabilityV32.selected,null)}
  a.w.state.lines[0].designation='Autre travail';a.w.renderQuoteLines();assert.equal(a.w.acjAvailabilityV32.selected,null);assert.equal(a.w.state.availabilityProposal,undefined);

  const big=await boot({lines:[line({qty:16})]});const invoice=JSON.stringify(big.w.state.lines);assert.equal(big.doc.getElementById('av32Duration').value,'16');event(big,'av32Persons','2');assert.equal(big.doc.getElementById('av32Parallel').hidden,false);assert.match(big.doc.getElementById('av32ParallelMath').textContent,/16 h.*2 personnes.*8 h/);await big.w.acjAvailabilityV32.search();assert.equal(big.calls.length,0);assert.match(big.doc.getElementById('av32Status').textContent,/parallèle/);parallel(big);big.setData(complete([plan({labor:960,persons:2})]));await big.w.acjAvailabilityV32.search();query=big.calls.at(-1).url.searchParams;assert.equal(query.get('labor_minutes'),'960');assert.equal(query.get('persons'),'2');assert.equal(query.get('parallel_confirmed'),'1');assert.equal(count(big),1);clickPlan(big);assert.equal(big.w.state.availabilityProposal.plan.planned_labor_minutes,960);assert.equal(big.w.state.availabilityProposal.plan.day_count,1);assert.equal(JSON.stringify(big.w.state.lines),invoice);
  const teamDraft=big.w.acjAvailabilityV32.getDraft(),teamReload=await boot({lines:[line({qty:16})]});assert.equal(teamReload.w.acjAvailabilityV32.restore(teamDraft),true);assert.equal(teamReload.doc.getElementById('av32Persons').value,'2');assert.equal(teamReload.doc.getElementById('av32ParallelConfirm').checked,false);assert.equal(teamReload.w.state.availabilityProposal.needs_recheck,true);await teamReload.w.acjAvailabilityV32.search();assert.equal(teamReload.calls.length,0,'Restored crew needs fresh parallel consent');
  event(big,'av32Duration','16','input');assert.equal(big.doc.getElementById('av32ParallelConfirm').checked,false);parallel(big);big.w.state.lines[0].meta='Nouveau périmètre';big.w.renderQuoteLines();assert.equal(big.doc.getElementById('av32ParallelConfirm').checked,false);event(big,'av32Persons','1');big.setData(complete([plan({labor:960})]));await big.w.acjAvailabilityV32.search();assert.equal(count(big),1);assert.equal(big.doc.querySelectorAll('.av32Segment').length,4);assert.match(big.doc.querySelector('.av32Plan').textContent,/autres plages/);clickPlan(big);assert.equal(big.w.state.availabilityProposal.plan.day_count,2);assert.equal(big.w.state.availabilityProposal.plan.segment_count,4);
  const short=await boot({lines:[line({qty:.5})]});event(short,'av32Persons','2');parallel(short);await short.w.acjAvailabilityV32.search();assert.equal(short.calls.length,0);assert.match(short.doc.getElementById('av32Status').textContent,/30 minutes.*personne/);

  for(const extra of [{unit:'forfait',pricingMethod:'flat'},{unit:'unité',pricingMethod:'quantity'},{unit:'h',pricingMethod:'flat'},{aiProvenance:{durationConfirmed:false}}]){const guard=await boot({lines:[line(extra)]});assert.equal(guard.doc.getElementById('av32Duration').value,'');await guard.w.acjAvailabilityV32.search();assert.equal(guard.calls.length,0);event(guard,'av32Duration','3','input');guard.setData(complete([plan()]));await guard.w.acjAvailabilityV32.search();assert.equal(count(guard),1)}
  const actual=await boot({mode:'bricol'});await actual.w.acjAvailabilityV32.search();assert.equal(actual.calls[0].url.searchParams.get('activity'),'jardin');const mixed=await boot({lines:[line(),line({id:'clean',activity:'menage',qty:16})]});await mixed.w.acjAvailabilityV32.search();assert.equal(mixed.calls.length,0);event(mixed,'av32Scope','menage');assert.equal(mixed.doc.getElementById('av32Duration').value,'16');event(mixed,'av32Persons','2');parallel(mixed);event(mixed,'av32Scope','jardin');assert.equal(mixed.doc.getElementById('av32ParallelConfirm').checked,false);

  const named=await boot();named.setData({...complete([]),employee_preference_required:true});await named.w.acjAvailabilityV32.search();assert.equal(named.doc.getElementById('av32Preferences').open,true);event(named,'av32Employee','Test Elodie Jean-Baptiste','input');assert.ok(named.doc.querySelector('input[data-employee-id="u"]'));choose(named,'u');named.setData(complete([plan({ids:['u']})]));await named.w.acjAvailabilityV32.search();assert.deepEqual(JSON.parse(named.calls.at(-1).url.searchParams.get('employee_ids')),['u']);assert.equal(count(named),1);assert.match(named.doc.querySelector('.av32Checks').textContent,/Métier salarié/);
  event(named,'av32Persons','2');event(named,'av32Duration','16','input');parallel(named);named.setData(complete([plan({labor:960,persons:2,ids:['u','b']})]));await named.w.acjAvailabilityV32.search();assert.equal(count(named),1,'Unknown named worker can be joined by a known worker');assert.deepEqual(JSON.parse(named.calls.at(-1).url.searchParams.get('employee_ids')),['u']);named.setData(complete([plan({labor:960,persons:2,ids:['a','c']})]));await named.w.acjAvailabilityV32.search();assert.equal(count(named),0,'Every required member must remain in the whole job');named.w.newQuote();assert.equal(named.doc.getElementById('av32Persons').value,'1');assert.equal(named.doc.getElementById('av32ParallelConfirm').checked,false);assert.equal(named.doc.getElementById('av32Employee').value,'');assert.equal(named.doc.querySelectorAll('input[data-employee-id]').length,0);
  const crews=await boot();crews.setData(complete([plan({ids:['a']}),plan({ids:['b']}),plan({ids:['c']})]));await crews.w.acjAvailabilityV32.search();assert.equal(count(crews),3,'Three full teams at the same times remain three distinct organizations');

  // Reject complete-looking plans with independently inconsistent structure/proof.
  const strict=await boot(),base=plan(),invalid=[];const bad=mutate=>{const copy=clone(base);mutate(copy);invalid.push(copy)};
  bad(p=>p.complete=false);bad(p=>p.crew[0].source='unknown');bad(p=>p.crew[0].activity_checked=false);bad(p=>p.segments[0].employee_ids=['b']);bad(p=>p.segments[0].date='2030-02-30');bad(p=>p.segments[0].start='25:00');bad(p=>{p.segments[0].start='11:00';p.segments[0].end='14:00'});bad(p=>{p.segments[0].start='07:00';p.segments[0].end='10:00'});bad(p=>{p.segments[0].start='16:00';p.segments[0].end='19:00'});bad(p=>p.segments[0].date='2030-01-13');bad(p=>p.segments[0].date='2030-03-01');bad(p=>p.planned_labor_minutes=179);bad(p=>p.onsite_minutes=179);bad(p=>p.day_count=2);bad(p=>p.segment_count=2);bad(p=>p.round_up_labor_minutes=1);for(const key of ['planning_complete','planning_checked','absences_checked','employee_profile_checked','employee_base_checked','client_base_checked','client_planning_checked'])bad(p=>p.segments[0].verification[key]=false);
  strict.setData(complete([base,...invalid]));await strict.w.acjAvailabilityV32.search();assert.equal(count(strict),1);assert.match(strict.doc.getElementById('av32Status').textContent,/exclues/);clickPlan(strict);const now=strict.w.Date.now;strict.w.Date.now=()=>now()+300001;assert.equal(strict.w.acjAvailabilityV32.selected,null);assert.equal(strict.w.state.availabilityProposal.needs_recheck,true);strict.w.Date.now=now;
  strict.setData({ok:true,checked_at:new Date().toISOString(),slots:[{date:'2030-01-07',start:'08:00',end:'11:00',source:'ogust',intervenant:'Test'}]});await strict.w.acjAvailabilityV32.search();assert.equal(count(strict),0);assert.match(strict.doc.getElementById('av32Status').textContent,/ancien créneau/);
  const rounded=await boot();event(rounded,'av32Duration',181/60,'input');event(rounded,'av32Persons','3');parallel(rounded);const roundedPlan=plan({labor:181,persons:3});rounded.setData(complete([roundedPlan]));await rounded.w.acjAvailabilityV32.search();assert.equal(count(rounded),1);assert.equal(roundedPlan.round_up_labor_minutes,2);const tooMuch=clone(roundedPlan);tooMuch.round_up_labor_minutes=3;rounded.setData(complete([tooMuch]));await rounded.w.acjAvailabilityV32.search();assert.equal(count(rounded),0);
  const full=await boot({lines:[line({qty:16})]});const incomplete=plan({labor:960});incomplete.segments.pop();incomplete.segment_count--;incomplete.onsite_minutes-=240;incomplete.planned_labor_minutes-=240;full.setData(complete([incomplete]));await full.w.acjAvailabilityV32.search();assert.equal(count(full),0);const overlap=plan({labor:960});overlap.segments[1].start='10:00';overlap.segments[1].end='14:00';full.setData(complete([overlap]));await full.w.acjAvailabilityV32.search();assert.equal(count(full),0);const crewChange=plan({labor:960});crewChange.segments[2].employee_ids=['b'];full.setData(complete([crewChange]));await full.w.acjAvailabilityV32.search();assert.equal(count(full),0);
  const cap=await boot({lines:[line({qty:9})]});const overCap=plan({labor:540,daily:540});overCap.daily_minutes=480;cap.setData(complete([overCap]));await cap.w.acjAvailabilityV32.search();assert.equal(count(cap),0);event(cap,'av32DailyHours','9');overCap.daily_minutes=540;cap.setData(complete([overCap]));await cap.w.acjAvailabilityV32.search();assert.equal(count(cap),1);
  const healthy=await boot();healthy.setData({...complete([plan()]),verification:{planning_complete:false},sources:{ogust:{available:true,queried:true},google:{available:false,queried:true,failed_employee_ids:['unused']}}});await healthy.w.acjAvailabilityV32.search();assert.equal(count(healthy),1,'Unrelated source failure cannot reject a proved healthy plan');
  const prefs=await boot();event(prefs,'av32Weekday','1');event(prefs,'av32Period','morning');prefs.setData(complete([plan(),plan({date:'2030-01-08'}),plan({start:780})]));await prefs.w.acjAvailabilityV32.search();assert.equal(count(prefs),1);assert.equal(prefs.calls.at(-1).url.searchParams.get('weekday'),'1');assert.equal(prefs.calls.at(-1).url.searchParams.get('period'),'morning');

  const legacy=await boot();const old={version:2,context:{...clone(remembered.context)},preferences:{duration_minutes:180,manual_duration:false,from:'2030-01-07',days:14,period:'any',weekday:''},proposal:{version:2,slot:{date:'2030-01-07',start:'08:00',end:'11:00',source:'ogust',intervenant:'Alex Test'},checked_at:'2020-01-01T00:00:00Z'}};event(legacy,'av32Persons','3');assert.equal(legacy.w.acjAvailabilityV32.restore(old),true);assert.equal(legacy.doc.getElementById('av32Persons').value,'1');assert.equal(legacy.w.acjAvailabilityV32.selected,null);assert.ok(legacy.w.state.availabilityProposal.legacy_slot);assert.equal(legacy.w.state.availabilityProposal.plan,undefined);assert.match(legacy.doc.getElementById('av32Selected').textContent,/Ancienne proposition pour une personne/);
  const pending=await boot(),release=pending.defer(),promise=pending.w.acjAvailabilityV32.search();await wait(0);event(pending,'av32Persons','2');release(complete([plan()]));await promise;assert.equal(count(pending),0);assert.equal(pending.doc.getElementById('av32Search').disabled,false);
  const context=await boot();await context.w.acjAvailabilityV32.search();clickPlan(context);event(context,'adresse','Nouvelle adresse','input');await wait(0);assert.equal(context.w.acjAvailabilityV32.selected,null);await context.w.acjAvailabilityV32.search();clickPlan(context);context.w.state.company='ACJ Services Lens';context.w.ogustClientChoiceV21.company='ACJ Services Lens';context.w.dispatchEvent(new context.w.CustomEvent('acj:company-changed'));assert.equal(context.w.acjAvailabilityV32.selected,null);assert.equal(context.doc.querySelectorAll('input[data-employee-id]').length,0);assert.equal(context.w.acjAvailabilityV32.restore(remembered),false);
  for(const app of apps)assert.ok(app.calls.every(call=>!call.init?.method||call.init.method==='GET'));
  console.log('Availability v50: full-job labor/team consent, fixed crews, exact required IDs, complete coverage/rounding/daycap/lunch/proofs, AI/manual guards, scope/context, distinct organizations, v3/legacy recheck, expiry and read-only API OK');
}finally{await wait(10);for(const app of apps)app.dom.window.close()}
