import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const nodes=new Map();
class Element{constructor(tag){this.tag=tag;this.children=[];this.style={};this.value='';this.parentElement={querySelector:()=>({textContent:''})}}set id(v){this._id=v;nodes.set(v,this)}get id(){return this._id}append(...xs){this.children.push(...xs)}replaceChildren(){this.children=[]}setAttribute(){}insertAdjacentElement(){}scrollIntoView(){}}
for(const id of ['presetChoices','serviceBuilder']){const e=new Element('div');e.id=id}
const rates=[{id:'hour',product:'garden',title:"Jardinage à l'heure",unit:'H',vat:20,price:47},{id:'flat',product:'flat',title:'Forfait Jardin',unit:'F',vat:20,price:90},{id:'unit',product:'unit',title:'Option Jardi',unit:'Q',vat:20,price:1.2}];
const state={mode:'jardin',company:'ACJ Services',activePreset:null,builderMethod:'hourly',lines:[]};let renders=0;const events={};
const ctx={state,MODES:{jardin:{presets:[{id:'autre_jardin',kind:'custom'}]}},document:{readyState:'complete',createElement:tag=>new Element(tag),getElementById:id=>nodes.get(id),querySelector:()=>null},acjOgustRates:{rates,load:async()=>true,assign(l,r){Object.assign(l,{ogustRateId:r.id,ogustProductLevelId:r.product,ogustProductCompany:state.company})}},choosePreset(id){state.activePreset=id;state.builderMethod='hourly';ctx.renderServiceBuilder()},renderServiceBuilder(){for(const id of ['builderDesignation','builderRate','builderFlat','builderHours'])nodes.delete(id);for(const id of ['builderDesignation',...(state.builderMethod==='flat'?['builderFlat']:['builderRate','builderHours'])]){const e=new Element('input');e.id=id;e.value=id==='builderHours'?'1':''}},addBuiltService(){const flat=state.builderMethod==='flat';state.lines.push({qty:flat?1:Number(nodes.get('builderHours').value),unit:flat?'forfait':'h',unitPriceTTC:Number(nodes.get(flat?'builderFlat':'builderRate').value),vat:10});state.activePreset=null},renderQuoteLines(){renders++},setMode(){},newQuote(){},goStep(){},addEventListener(name,fn){events[name]=fn}};ctx.window=ctx;
vm.runInNewContext(fs.readFileSync('ogust-picker-v41.js','utf8'),ctx);await new Promise(r=>setImmediate(r));
const box=nodes.get('ogPicker41'),input=box.children.find(x=>x.tag==='input');input.value='jard heure';input.oninput();let buttons=nodes.get('ogPickerResults41').children;assert.equal(buttons.length,1);buttons[0].onclick();assert.equal(nodes.get('builderRate').value,47);nodes.get('builderHours').value='3';nodes.get('builderRate').value='55';ctx.addBuiltService();let line=state.lines.at(-1);assert.equal(line.qty,3);assert.equal(line.unitPriceTTC,55);assert.equal(line.vat,20);assert.equal(line.ogustRateId,'hour');
input.value='forfait';input.oninput();nodes.get('ogPickerResults41').children[0].onclick();assert.equal(state.builderMethod,'flat');assert.equal(nodes.get('builderFlat').value,90);ctx.addBuiltService();line=state.lines.at(-1);assert.equal(line.unit,'forfait');assert.equal(line.ogustRateId,'flat');
input.value='option';input.oninput();nodes.get('ogPickerResults41').children[0].onclick();nodes.get('builderHours').value='2';ctx.addBuiltService();line=state.lines.at(-1);assert.equal(line.qty,2);assert.equal(line.unit,'unité');assert.equal(line.ogustRateId,'unit');
input.value='aucun résultat';input.oninput();assert.equal(nodes.get('ogPickerResults41').children.length,0);
input.value='heure';input.oninput();nodes.get('ogPickerResults41').children[0].onclick();state.company='ACJ Services Lens';events['acj:company-changed']();ctx.addBuiltService();assert.equal(state.lines.at(-1).ogustRateId,undefined);
assert.equal(renders,3);console.log('Early Ogust picker: search, hourly/flat/unit quantities, editable prices, VAT and company reset OK');
