const API='https://acj-ogust-proxy.vercel.app';
const HISTORY_START='2026-01-01';
const staff=[
  {key:'jb',name:'Jean-Baptiste',calendar:'Planning JB'},
  {key:'vincent',name:'Vincent',calendar:'Planning Vincent'},
  {key:'yohann',name:'Yohann',calendar:'Planning Yohann'},
  {key:'thomas',name:'Thomas',calendar:'Planning ACJ services Thomas'}
];
const S={employee:'jb',historyEmployee:'jb',day:isoToday(),customer:null,google:{jb:[],vincent:[],yohann:[],thomas:[]},mode:{jb:'loading',vincent:'waiting',yohann:'waiting',thomas:'waiting'},local:loadLocal()};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function isoToday(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}
function addDays(iso,n){const d=new Date(iso+'T12:00:00');d.setDate(d.getDate()+n);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}
function monday(iso){const d=new Date(iso+'T12:00:00');d.setDate(d.getDate()-((d.getDay()+6)%7));d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}
function frDate(iso,opt={weekday:'long',day:'numeric',month:'long'}){return new Intl.DateTimeFormat('fr-FR',opt).format(new Date(iso+'T12:00:00'))}
function mins(a,b){if(!a||!b)return 0;const A=a.split(':').map(Number),B=b.split(':').map(Number);return B[0]*60+B[1]-A[0]*60-A[1]}
function duration(a,b){const m=Math.max(0,mins(a,b));return `${Math.floor(m/60)} h${m%60?' '+String(m%60).padStart(2,'0'):''}`}
function phone(text=''){return String(text).match(/(?:\+33|0)[1-9](?:[ .-]?\d{2}){4}/)?.[0]||''}
function city(address=''){return String(address).match(/\b\d{5}\s+([^,]+)/)?.[1]?.trim()||''}
function service(title='',desc=''){const t=norm(title+' '+desc);if(t.includes('taille')&&t.includes('haie'))return'Taille de haies';if(t.includes('tonte')||t.includes('pelouse'))return'Jardinage';if(t.includes('desherb'))return'Désherbage';if(t.includes('debrou'))return'Débroussaillage';if(t.includes('karcher')||t.includes('nettoyage'))return'Nettoyage extérieur';if(/^appeler/.test(t))return'Rappel / contact';if(/^cp$/.test(t))return'Congé';return'Intervention'}
function loadLocal(){try{return JSON.parse(localStorage.getItem('acj-terrain-v2')||'[]')}catch{return[]}}
function saveLocal(){localStorage.setItem('acj-terrain-v2',JSON.stringify(S.local))}
function employee(key){return staff.find(x=>x.key===key)||staff[0]}
function all(key){return [...S.google[key],...S.local.filter(x=>x.employee_key===key)].sort((a,b)=>(a.date+(a.start||'')).localeCompare(b.date+(b.start||'')))}
function normalizeGoogle(r,key,mode='live'){const title=r.title||'Sans titre',desc=r.description||'',address=r.address||'';return{local_id:`g-${key}-${r.google_event_id}`,google_event_id:r.google_event_id,employee_key:key,client:title,phone:phone(desc),address,city:city(address),instructions:desc,service:service(title,desc),date:r.date,start:r.start||'',end:r.end||'',all_day:!!r.all_day,source:'google',source_mode:mode,status:'planned',km:0,html_link:r.html_link||''}}

async function seedJB(){try{const r=await fetch('./planning-jb-snapshot.json',{cache:'no-store'}),d=await r.json();if(S.mode.jb!=='live'){S.google.jb=(d.events||[]).map(x=>normalizeGoogle(x,'jb','snapshot'));S.mode.jb='snapshot'}}catch{S.mode.jb='waiting'}}
async function sync(key,history=false){const previous=S.mode[key];S.mode[key]='loading';notices();try{const u=new URL(API+'/api/terrain-calendar');u.searchParams.set('employee',key);u.searchParams.set('from',history?HISTORY_START:addDays(isoToday(),-21));u.searchParams.set('to',addDays(isoToday(),history?180:90));const r=await fetch(u);const d=await r.json();if(!r.ok)throw new Error(d.error||'CALENDAR');S.google[key]=(d.events||[]).map(x=>normalizeGoogle(x,key));S.mode[key]='live'}catch{if(key==='jb'&&S.google.jb.length)S.mode.jb='snapshot';else S.mode[key]=previous==='live'?'live':'waiting'}render();historyRender();notices()}

function badge(i){if(i.client_source==='manual')return'<span class="source-badge manual">Hors Ogust</span>';return i.source==='google'?'<span class="source-badge">Google</span>':'<span class="source-badge">Terrain</span>'}
function card(i){const when=i.all_day?'Journée':esc(i.start||'—');const sub=i.all_day?'':`${esc(i.end||'')}<br>${esc(duration(i.start,i.end))}`;return`<article class="intervention-card"><div class="intervention-top"><div class="time-block"><strong>${when}</strong><span>${sub}</span></div><div><div class="client-name">${esc(i.client)} ${badge(i)}</div><div class="service-name">${esc(i.service)}</div><div class="city">${esc(i.address||i.instructions||'')}</div></div><span class="badge">${i.status==='done'?'Terminée':'Prévue'}</span></div><div class="card-actions"><button class="secondary-btn open-intervention" data-id="${esc(i.local_id)}">Ouvrir</button></div></article>`}
function renderToday(){const L=all(S.employee).filter(x=>x.date===isoToday());$('todayTitle').textContent=frDate(isoToday()).replace(/^./,c=>c.toUpperCase());$('statCount').textContent=L.length;$('statHours').textContent=(L.reduce((s,x)=>s+mins(x.start,x.end),0)/60).toLocaleString('fr-FR',{maximumFractionDigits:1})+' h';$('statKm').textContent=L.reduce((s,x)=>s+Number(x.km||0),0)+' km';$('todayList').innerHTML=L.length?L.map(card).join(''):'<div class="empty-state">Aucune intervention aujourd’hui.</div>';$('todaySource').textContent=S.mode[S.employee]==='live'?'Google live':S.mode[S.employee]==='snapshot'?'Copie Google':'Google'}
function renderPlanning(){const m=monday(S.day),days=[0,1,2,3,4,5,6].map(n=>addDays(m,n));$('weekDays').innerHTML=days.map(d=>`<button class="day-chip ${d===S.day?'active':''}" data-date="${d}"><span>${frDate(d,{weekday:'short'})}</span><strong>${Number(d.slice(8))}</strong></button>`).join('');const L=all(S.employee).filter(x=>x.date===S.day);$('planningList').innerHTML=L.length?L.map(card).join(''):'<div class="empty-state">Aucune intervention ce jour.</div>'}
function notices(){const m=S.mode[S.employee],b=$('calendarNotice');b.hidden=false;b.className='notice compact '+(m==='live'?'good':m==='snapshot'?'warn':'');b.textContent=m==='live'?'Google Agenda connecté en direct.':m==='snapshot'?'Planning JB réel affiché depuis la copie importée. Connexion Google live encore à autoriser.':m==='loading'?'Lecture de Google Agenda…':'Agenda prêt. Autorisation Google serveur encore nécessaire.';const hm=S.mode[S.historyEmployee],h=$('historySyncStatus');h.className='notice compact '+(hm==='live'?'good':hm==='snapshot'?'warn':'');h.textContent=hm==='live'?'Historique Google live chargé depuis le 1er janvier 2026.':hm==='snapshot'?'Historique récent réel de Planning JB affiché. Le mode live reprendra automatiquement tout depuis le 1er janvier 2026.':hm==='loading'?'Chargement de l’historique Google…':'Historique prêt après autorisation Google.'}
function render(){const e=employee(S.employee);$('userLabel').textContent=e.calendar+' · Terrain';renderToday();renderPlanning();notices()}

function historyRender(){const q=norm($('historySearch')?.value||'');let L=all(S.historyEmployee).filter(x=>x.source==='google'&&x.date<=isoToday()).sort((a,b)=>(b.date+b.start).localeCompare(a.date+a.start));if(q)L=L.filter(x=>norm(x.client+' '+x.address+' '+x.instructions+' '+x.service).includes(q));$('historyCount').textContent=L.length+' intervention'+(L.length>1?'s':'')+' affichée'+(L.length>1?'s':'');if(!L.length){$('historyList').innerHTML='<div class="empty-state">Aucun historique disponible.</div>';return}const G={};L.forEach(x=>(G[x.date.slice(0,7)]??=[]).push(x));$('historyList').innerHTML=Object.entries(G).map(([m,rows])=>`<section class="history-month"><div class="history-month-title">${esc(frDate(m+'-01',{month:'long',year:'numeric'}))}</div>${rows.map(i=>`<article class="history-row open-intervention" data-id="${esc(i.local_id)}"><div class="history-date">${esc(frDate(i.date,{weekday:'short'}))}<strong>${i.date.slice(8)}</strong>${esc(i.start||'Journée')}</div><div class="history-main"><strong>${esc(i.client)} ${badge(i)}</strong>${i.instructions?`<p>${esc(i.instructions)}</p>`:''}<div class="history-meta">${esc([i.service,i.address].filter(Boolean).join(' · '))}</div></div></article>`).join('')}</section>`).join('')}

function fillStaff(){const opts=staff.map(x=>`<option value="${x.key}">${esc(x.name)} — ${esc(x.calendar)}</option>`).join('');$('employeeFilter').innerHTML=opts;$('historyEmployeeFilter').innerHTML=opts;$('employeeSelect').innerHTML='<option value="">Choisir</option>'+opts;$('employeeFilter').value=S.employee;$('historyEmployeeFilter').value=S.historyEmployee;$('employeeSelect').value=S.employee}
function showOgust(c){S.customer={...c,source:'ogust'};$('customerId').value=c.id_customer;$('clientSource').value='ogust';$('customerSearch').value=c.label;$('customerResults').hidden=true;$('manualCustomerBtn').hidden=true;$('manualCustomerPanel').hidden=true;$('selectedCustomer').hidden=false;$('selectedCustomer').innerHTML=`<strong>${esc(c.label)} — ${esc(c.city||'')}</strong><span>${esc(c.phone||'Sans téléphone')}</span><span>${esc(c.address||'')}</span><span>Client Ogust n° ${esc(c.id_customer)}</span>`;$('serviceAddress').value=c.address||''}
function showManual(){const name=$('manualName').value.trim();if(name.length<2)return alert('Nom du client obligatoire.');S.customer={id_customer:null,label:name,phone:$('manualPhone').value.trim(),address:$('manualAddress').value.trim(),city:$('manualCity').value.trim(),source:'manual'};$('clientSource').value='manual';$('customerSearch').value=name;$('selectedCustomer').hidden=false;$('selectedCustomer').innerHTML=`<strong>${esc(name)} ${badge({client_source:'manual'})}</strong><span>${esc(S.customer.phone||'Sans téléphone')}</span><span>${esc(S.customer.address||'')}</span>`;$('serviceAddress').value=S.customer.address;$('manualCustomerPanel').hidden=true}
let timer;$('customerSearch').addEventListener('input',e=>{S.customer=null;$('selectedCustomer').hidden=true;$('manualCustomerPanel').hidden=true;clearTimeout(timer);const q=e.target.value.trim(),box=$('customerResults');if(q.length<2){box.hidden=true;$('manualCustomerBtn').hidden=true;return}timer=setTimeout(async()=>{box.hidden=false;box.innerHTML='<div class="search-result"><span>Recherche Ogust…</span></div>';let rows=[],down=false;try{const r=await fetch(API+'/api/ogust-customer?q='+encodeURIComponent(q)),d=await r.json();if(!r.ok)down=true;else rows=d.customer_candidates||[]}catch{down=true}box._rows=rows;box.innerHTML=rows.length?rows.map((c,n)=>`<div class="search-result customer-pick" data-i="${n}"><strong>${esc(c.label)} — ${esc(c.city||'')}</strong><span>${esc(c.phone||'')} · ${esc(c.address||'')}</span></div>`).join(''):`<div class="search-result"><strong>${down?'Ogust indisponible':'Aucun client trouvé'}</strong><span>La saisie exceptionnelle reste possible en dernier recours.</span></div>`;$('manualCustomerBtn').hidden=false},250)});
$('customerResults').addEventListener('click',e=>{const p=e.target.closest('.customer-pick');if(p)showOgust($('customerResults')._rows[Number(p.dataset.i)])});$('manualCustomerBtn').onclick=()=>{$('customerResults').hidden=true;$('manualCustomerPanel').hidden=false;$('manualName').value=$('customerSearch').value.trim()};$('useManualCustomerBtn').onclick=showManual;

$('newInterventionForm').addEventListener('submit',e=>{e.preventDefault();const st=$('createStatus');if(!S.customer){st.hidden=false;st.className='notice warn';st.textContent='Sélectionne un client Ogust ou utilise la saisie exceptionnelle.';return}const start=$('startTime').value,end=$('endTime').value;if(mins(start,end)<=0){st.hidden=false;st.className='notice warn';st.textContent='L’heure de fin doit être après le début.';return}const key=$('employeeSelect').value;const i={local_id:'loc-'+Date.now(),employee_key:key,id_employee:null,id_customer:S.customer.id_customer||null,id_service:null,google_event_id:null,client_source:S.customer.source,client:S.customer.label,phone:S.customer.phone||'',address:$('serviceAddress').value.trim(),city:S.customer.city||'',service:$('serviceType').value,date:$('serviceDate').value,start,end,instructions:$('instructions').value.trim(),source:'local',status:'planned',km:0,sync_status:S.customer.source==='manual'?'needs_customer_match':'pending'};S.local.push(i);saveLocal();render();st.hidden=false;st.className='notice '+(S.customer.source==='manual'?'warn':'good');st.textContent=S.customer.source==='manual'?'Intervention enregistrée. Client hors Ogust : rapprochement obligatoire avant synchronisation Ogust.':'Intervention enregistrée avec le client Ogust. Écriture Google/Ogust à activer ensuite.';e.target.reset();S.customer=null;$('selectedCustomer').hidden=true;$('manualCustomerPanel').hidden=true;$('manualCustomerBtn').hidden=true;$('serviceDate').value=isoToday();$('startTime').value='08:00';$('endTime').value='10:00';$('employeeSelect').value=S.employee});

function openItem(id){const i=staff.flatMap(x=>all(x.key)).find(x=>x.local_id===id);if(!i)return;$('dialogTitle').textContent=i.client;const gps='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(i.address||'');$('dialogBody').innerHTML=`<div class="detail-grid"><div class="detail-box"><span>Source</span><strong>${i.source==='google'?'Google Agenda':'ACJ Terrain'} ${badge(i)}</strong></div><div class="detail-box"><span>Prestation</span><strong>${esc(i.service)}</strong></div><div class="detail-box"><span>Horaires</span><strong>${esc(i.start||'Journée')} ${i.end?'→ '+esc(i.end):''}</strong></div><div class="detail-box"><span>Adresse</span><strong>${esc(i.address||'Non renseignée')}</strong>${i.address?`<div class="card-actions"><a class="secondary-btn" href="${gps}" target="_blank">GPS</a></div>`:''}</div><div class="detail-box"><span>Consignes</span><strong>${esc(i.instructions||'Aucune consigne')}</strong></div><div class="photo-grid"><div class="photo-box">Photo avant<br>＋ Ajouter</div><div class="photo-box">Photo après<br>＋ Ajouter</div></div>${i.source==='google'?'<div class="notice compact">Lecture seule Google pour cette étape.</div>':''}</div>`;$('interventionDialog').showModal()}
document.addEventListener('click',e=>{const n=e.target.closest('[data-nav]');if(n){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('screen-'+n.dataset.nav).classList.add('active');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.nav===n.dataset.nav));if(n.dataset.nav==='history')historyRender()}const d=e.target.closest('.day-chip');if(d){S.day=d.dataset.date;renderPlanning()}const o=e.target.closest('.open-intervention');if(o)openItem(o.dataset.id);const t=e.target.closest('.tool-card');if(t){$('toolStatus').hidden=false;$('toolStatus').textContent=t.dataset.tool+' : module préparé.'}});
$('employeeFilter').onchange=e=>{S.employee=e.target.value;S.day=isoToday();$('employeeSelect').value=S.employee;render();sync(S.employee)};$('historyEmployeeFilter').onchange=e=>{S.historyEmployee=e.target.value;historyRender();sync(S.historyEmployee,true)};$('historySearch').oninput=historyRender;$('refreshHistoryBtn').onclick=()=>sync(S.historyEmployee,true);$('closeDialog').onclick=()=>$('interventionDialog').close();
$('serviceDate').value=isoToday();$('startTime').value='08:00';$('endTime').value='10:00';
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('installBtn').hidden=false});$('installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('installBtn').hidden=true}};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
fillStaff();(async()=>{await seedJB();render();historyRender();sync('jb',true)})();
